---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-instance-test-deployment
  namespace: challenges
spec:
  selector:
    matchLabels:
      app: nginx-instance-test
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-instance-test
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-instance-test
  namespace: challenges
spec:
  selector:
    app: nginx-instance-test
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 80
---
