# Cursed shit
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: instancedchallenges.k8s.maplebacon.org
spec:
  group: k8s.maplebacon.org
  versions:
    - name: unstable
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                challengeTemplate:
                  type: string
  scope: Namespaced
  names:
    plural: instancedchallenges
    singular: instancedchallenge
    kind: InstancedChallenge
    shortNames:
    - instchal
