apiVersion: "k8s.maplebacon.org/unstable"
kind: InstancedChallenge
metadata:
  name: nginx
spec:
  resources:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: nginx-deployment
      namespace: challenges
    spec:
      selector:
        matchLabels:
          app: nginx
      replicas: 2
      template:
        metadata:
          labels:
            app: nginx
        spec:
          containers:
            - name: nginx
              image: nginx:1.14.2
              ports:
                - containerPort: 80
  - apiVersion: v1
    kind: Service
    metadata:
      name: nginx-service
      namespace: challenges
    spec:
      selector:
        app: nginx
      ports:
        - name: http
          protocol: TCP
          port: 8080
          targetPort: 80
  - apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: nginx
      namespace: challenges
      annotations:
        cert-manager.io/issuer: "letsencrypt-prod"
    spec:
      ingressClassName: nginx
      tls:
        - hosts:
            - nginx-test.ctf.maplebacon.org
          secretName: nginx-test-tls
      rules:
        - host: nginx-test.ctf.maplebacon.org
          http:
            paths:
              - path: /
                pathType: Prefix
                backend:
                  service:
                    name: nginx-service
                    port:
                      number: 8080
  - apiVersion: cert-manager.io/v1
    kind: Issuer
    metadata:
      name: letsencrypt-prod
      namespace: challenges
    spec:
      acme:
        # The ACME server URL
        server: https://acme-v02.api.letsencrypt.org/directory
        # Email address used for ACME registration
        email: bensonyang1999@gmail.com
        # Name of a secret used to store the ACME account private key
        privateKeySecretRef:
          name: letsencrypt-prod
        # Enable the HTTP-01 challenge provider
        solvers:
          - http01:
              ingress:
                class: nginx
