apiVersion: "k8s.maplebacon.org/unstable"
kind: InstancedChallenge
metadata:
  name: blade-runner
  namespace: challenges
spec:
  challengeTemplate: |
    ---
    apiVersion: v1
    kind: Service
    metadata:
      name: blade-runner-{{.ID}}
      namespace: challenges
    spec:
      ports:
        - name: web
          port: 6969
          targetPort: 6969
          protocol: TCP
      selector:
        app: blade-runner-{{.ID}}
    ---
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: blade-runner-{{.ID}}
      labels:
        app: blade-runner-{{.ID}}
      namespace: challenges
    spec:
      selector:
        matchLabels:
          app: blade-runner-{{.ID}}
      replicas: 1
      template:
        metadata:
          labels:
            app: blade-runner-{{.ID}}
        spec:
          enableServiceLinks: false
          automountServiceAccountToken: false
          containers:
            - name: blade-runner
              image: us.gcr.io/maplectf/blade-runner:latest
              imagePullPolicy: Always
              ports:
                - containerPort: 6969
                  name: web
              securityContext:
                allowPrivilegeEscalation: false
                privileged: false
              resources:
                requests:
                  cpu: "75m"
                  memory: "70Mi"
                limits:
                  cpu: "250m"
                  memory: "100Mi"
            - name: redis
              image: redis:latest
              imagePullPolicy: Always
              ports:
                - containerPort: 6379
                  name: redis
              securityContext:
                allowPrivilegeEscalation: false
                privileged: false
    ---
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: blade-runner-{{.ID}}
      namespace: challenges
      annotations:
        certmanager.k8s.io/issuer: "letsencrypt-prod"
        certmanager.k8s.io/acme-challenge-type: dns01
    spec:
      ingressClassName: challenges-nginx
      tls:
        - hosts:
          - "{{.ID}}.blade-runner.ctf.maplebacon.org"
          secretName: blade-runner-tls
      rules:
        - host: {{.ID}}.blade-runner.ctf.maplebacon.org
          http:
            paths:
              - path: /
                pathType: Prefix
                backend:
                  service:
                    name: blade-runner-{{.ID}}
                    port:
                      number: 6969